FROM python:3.10-slim

RUN echo 'Acquire::http::Pipeline-Depth "0"; Acquire::http::No-Cache true;' > /etc/apt/apt.conf.d/99fixbadproxy

RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./src /app/src
COPY pipeline_worker_main.py .
COPY requirements.pipeline-worker.txt .

RUN pip install --no-cache-dir -r requirements.pipeline-worker.txt

CMD ["python", "pipeline_worker_main.py"]
