FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./src /app/src
COPY file_watcher_main.py .
COPY requirements.file-watcher.txt .

RUN pip install --no-cache-dir -r requirements.file-watcher.txt

CMD ["python", "file_watcher_main.py"]
