FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./src /app/src
COPY requirements.monitor.txt .

RUN pip install --no-cache-dir -r requirements.monitor.txt

CMD ["python", "src/ingestion/monitor.py"]
